/-
Copyright (c) 2026 George A. Constantinides. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: George A. Constantinides (selection, specification), Claude (formalisation, proof)
-/
-- Skeleton for a new result. Copy to `MiscMath/<Area>/<Result>.lean`, fill in, and add
-- the corresponding `import` line to `MiscMath.lean` (alphabetical order).
--
-- Keep the `Authors:` line above as it is: Mathlib's header linter (active here via
-- `weak.linter.mathlibStandardSet` in `lakefile.toml`) requires one on every module that
-- `MiscMath.lean` imports, and the split records the division of work the README
-- describes. The linter rejects ` and `, double spaces, and a trailing period, so
-- separate contributions with commas.
--
-- This file lives under `docs/` and is not compiled; it is not part of the lean_lib.
import Mathlib.Tactic

/-!
# <Name of the result>

## Informal statement

<The claim in English, precise enough that a reader can compare it against the Lean
statement below without reading the proof. This is the primary artefact of the file:
the proof is machine-checked, the correspondence between this paragraph and the Lean
statement is not.>

## Source

<Citation: textbook and section, paper, or Wikipedia. Needed so a reader can check that
the informal statement above is actually the classical theorem it claims to be.>

## Relation to Mathlib

<Optional. If Mathlib already has this, or has most of it, say so and say what this file
adds — a different form, a packaging, a special case. If a new definition is introduced
here, state why Mathlib's vocabulary was insufficient and give the characterisation lemma
that ties the new definition back to it.>

## Provenance

Result selected and specified by George A. Constantinides, who has read the Lean statement
below against the informal claim above on a best-effort basis. The statement and its
proof were generated by Claude; the proof is read by nobody. Both are kernel-verified
and axiom-audited. A best-effort read is not a review — satisfy yourself that the
statement says what you need before relying on it. See the repository README.

Before that read, the Lean statement was read back blind: rendered into English by an
agent given the statement and nothing else — no informal statement, no source, no
docstring — and the rendering compared against the informal statement above. <Say here
what the read-back surfaced, or that it agreed.>
-/

namespace MiscMath.<Area>

/-- **<Name>.** <One-line docstring. State the mathematical content, not the proof
technique.> -/
theorem foo : True := trivial

/-! ## Sanity checks

Guards against the ways a correct proof can still accompany a useless statement. These
are `example`s: elaborated by the build, so one that stops holding breaks it, and
exporting no names. They are *not* reached by the axiom audit, which walks the named
declarations a module contributes to the environment, and an `example` contributes
none. What covers them instead is the textual escape-hatch scan in
`scripts/check-conventions.sh`, which reads the file rather than the environment.
-/

section Sanity

-- REQUIRED if the theorem has hypotheses: exhibit values satisfying all of them
-- simultaneously. Contradictory hypotheses make a theorem vacuously true, and this is
-- the most likely way for a machine-generated statement to be worthless while passing
-- every other check. Include universally quantified hypotheses, which are the easiest
-- place for an unsatisfiable assumption to hide.
example : ∃ n : ℕ, 0 < n := ⟨1, by norm_num⟩

-- REQUIRED where the conclusion has a concrete instance: confirm it at one, computed by
-- `decide` or `norm_num`, i.e. independently of the proof above. If the statement has
-- drifted from its intent, this is usually where it shows.
--
-- Some conclusions have no concrete instance to confirm. A limit, an asymptotic rate,
-- an existence claim with no computable witness: there is no value to evaluate, and no
-- amount of care makes one appear. Then this is not waived but REPLACED, and the
-- replacement is equally required — pin down every ingredient of the conclusion that
-- does have a concrete value. For a limit that means the value approached, the object
-- whose behaviour is described, and each translation between the informal notion and
-- the Lean one, since a translation is where drift actually happens. Say in a comment
-- which ingredient each example pins, so a reader can see the conclusion was covered
-- piecewise rather than skipped.
example : True := trivial

-- RECOMMENDED where applicable: show that a bound is sharp, that a hypothesis cannot be
-- dropped, or that the statement is not accidentally symmetric — anything that pins the
-- statement down to the one you meant.

end Sanity

end MiscMath.<Area>
