/-
Copyright (c) 2026 George Constantinides. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
-- Skeleton for a new result. Copy to `MiscMath/<Area>/<Result>.lean`, fill in, and add
-- the corresponding `import` line to `MiscMath.lean` (alphabetical order).
--
-- This file lives under `docs/` and is not compiled; it is not part of the lean_lib.
import Mathlib.Tactic

/-!
# <Name of the result>

## Informal statement

<The claim in English, precise enough that a reader can compare it against the Lean
statement below without reading the proof. This is the primary artefact of the file:
the proof is machine-checked, the correspondence between this paragraph and the Lean
statement is not.>

## Source

<Citation: textbook and section, paper, or Wikipedia. Needed so a reader can check that
the informal statement above is actually the classical theorem it claims to be.>

## Relation to Mathlib

<Optional. If Mathlib already has this, or has most of it, say so and say what this file
adds — a different form, a packaging, a special case. If a new definition is introduced
here, state why Mathlib's vocabulary was insufficient and give the characterisation lemma
that ties the new definition back to it.>

## Provenance

Result selected and specified by George Constantinides. The Lean statement and its
proof were generated by Claude; they are kernel-verified and axiom-audited, and have
not been read by a human. See the repository README for what that does and does not
mean.
-/

namespace MiscMath.<Area>

/-- **<Name>.** <One-line docstring. State the mathematical content, not the proof
technique.> -/
theorem foo : True := trivial

/-! ## Sanity checks

Guards against the ways a correct proof can still accompany a useless statement. These
are `example`s: elaborated by the build and covered by the axiom audit, but exporting
no names.
-/

section Sanity

-- REQUIRED if the theorem has hypotheses: exhibit values satisfying all of them
-- simultaneously. Contradictory hypotheses make a theorem vacuously true, and this is
-- the most likely way for a machine-generated statement to be worthless while passing
-- every other check. Include universally quantified hypotheses, which are the easiest
-- place for an unsatisfiable assumption to hide.
example : ∃ n : ℕ, 0 < n := ⟨1, by norm_num⟩

-- REQUIRED: confirm the conclusion at a concrete value, computed by `decide` /
-- `norm_num` / `native_decide`-free evaluation, i.e. independently of the proof above.
-- If the statement has drifted from its intent, this is usually where it shows.
example : True := trivial

-- RECOMMENDED where applicable: show that a bound is sharp, that a hypothesis cannot be
-- dropped, or that the statement is not accidentally symmetric — anything that pins the
-- statement down to the one you meant.

end Sanity

end MiscMath.<Area>
